language: python

python: 3.7.3

# Disable sudo to speed up the build
#sudo: false

install:
  - pip install -r requirements.txt

script:
  # Set Codacy token (code quality service)
  - export CODACY_PROJECT_TOKEN=2fa2194d57564a68b37796c4eda2dd96

  # Generate a coverage report in xml format
  - pytest --cov-report=xml --cov=.

  # Submit coverage report to Codacy
  - python-codacy-coverage -r coverage.xml
